### PR TITLE
14 manage multiple sessions with user auth

### LINKED ISSUE #14: Manage multiple sessions with user auth

### PR DESCRIPTION
**Pull request by antolinos**
The following list should now been populated with the shared sessions thanks to the emit done at AbstractLIMS
image

### CODE REVIEW

**Comment by marcus-oscarsson** [comment]
Thanks !

**Comment by axelboc** [comment]
Might be worth pulling upstream changes before merging (i.e. functional component).

**Comment by marcus-oscarsson** [comment]
@axelboc and @antolinos, my apologies I managed to loose a PR from Axel two weeks ago. That was why I was a bit surprised yesterday @antolinos, (and was looking for things that I could not find). 

I reopened the PR on `mxcubeweb` and then Ill rebase and take the necessary commits from this PR.

Again really sorry for the confusion, thanks for the PR's

**Comment by antolinos** [comment]
@marcus-oscarsson No problemo!
@axelboc Please, if you have the chance, do not hesitate to review this. Because I'm not using state and props for a long time I admit that I have forgotten how  they work together. So, I am pretty sure there is room for improvement. The feature was that we need to refresh the list of sessions for the user A when a user B logs in with the sessions that A and B share. Thanks!

**Comment by marcus-oscarsson** [comment]
Alright, so I thinks what @axelboc did already solves the problem, as you can see on:

  https://github.com/mxcube/esrf-mxcubeweb/blob/d2f2414b09e7984848917ab7169db70b50288cd6/ui/src/components/LoginForm/SelectProposal.jsx#L24

So `proposalList` comes from the right place and should then be updated accordingly.

It only leaves out the commit the removes the user from the internal LIMS structures when we logout. If that makes sense.

**Comment by marcus-oscarsson** [comment]
Thanks again, and my apologies for my clumsiness :/

**Comment by axelboc** [comment]
Great!

**Pull request merged**
